ALTER SESSION SET CURRENT_SCHEMA=SWIP;

ALTER TABLE DM_TITRI_CONTRAT RENAME COLUMN ORIG_CONTRAT_TX TO ORIG_CONTRAT_TX_OLD;
ALTER TABLE DM_TITRI_CONTRAT ADD ORIG_CONTRAT_TX NUMBER(10,7);

alter session set nls_date_format = 'DD/MM/YYYY';