MERGE INTO TABLE1 A
      USING
      (SELECT  CLE,VAR1,VAR2
              From TABLE2 B
      )B
      ON(A.CLE = B.CLE)
		WHEN MATCHED THEN 
				UPDATE SET
					A.VAR1 = B.VAR1,
					A.VAR2 = B.VAR2;
		WHEN NOT MATCHED THEN
				INSERT (CLE,VAR1,VAR2)  VALUES (B.CLE,B.VAR1,B.VAR2)
    ;
  COMMIT;